farbox/FarboxWeb/urls.py
from django.conf.urls import patterns, url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index', views.index, name='index'),
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^upload', views.upload, name='upload'),
    url(r'^home', views.home, name='home'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^download', views.download, name='download'),
    url(r'^delete_file', views.delete_file, name='delete_file'),
    url(r'^share_file', views.share_file, name='share_file'),
    url(r'^share_page', views.share_page, name='share_page'),
    url(r'^save_to_mine', views.save_to_mine, name='save_to_mine'),
]

farbox/account/urls.py
from django.conf.urls import patterns, url, include
from account import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
]

farbox/farbox/urls.py
from django.conf.urls import url, patterns, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('FarboxWeb.urls', namespace='FarboxWeb')),
]

farbox/FarboxWeb/models.py
from django.db import models

# Create your models here.


class RealFile(models.Model):
    file_name = models.CharField(max_length=200)
    file_hash = models.CharField(max_length=200, unique=True, primary_key=True)
    file_size = models.BigIntegerField()


class VirtualFile(models.Model):
    realfilename = models.CharField(max_length=200, null=True)
    path_id = models.IntegerField(primary_key=True)
    parent_id = models.IntegerField(default=0)
    path_name = models.CharField(max_length=200)
    file_size = models.IntegerField(null=True)
    upload_time = models.DateTimeField(auto_now=True)
    is_file = models.BooleanField(default=False)


class ShareInfo(models.Model):
    share_key = models.CharField(max_length=200, null=False, unique=True, primary_key=True)
    path_id = models.IntegerField(null=False)

farbox/FarboxWeb/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordResetForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    """
    用户登录表单
    """
    remember_me = forms.BooleanField(label='下次自动登录', initial=False, required=False)


class RegistrationForm(UserCreationForm):
    """
    新用户注册表单
    """

    email = forms.EmailField(help_text='用户账号认证和密码重置')

    def clean_email(self):
        """
        确保注册邮箱的唯一性
        """
        value = self.cleaned_data['email']
        qs = User.objects.filter(email__iexact=value)
        if not qs.exists():
            return value
        raise forms.ValidationError('邮箱已被注册,请更换邮箱')


class UploadForm(forms.Form):
    """
    上传文件表单
    """
    file = forms.FileField(label='文件名', max_length=200)

farbox/FarboxWeb/views.py
from django.shortcuts import render
from django import forms
from django.contrib import messages
from django.shortcuts import render_to_response, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_user, logout as logout_user
from django.http import HttpResponse, HttpResponseRedirect
from . import FileManager
from .models import VirtualFile, ShareInfo, RealFile
from .forms import LoginForm, RegistrationForm, UploadForm
from django.http import StreamingHttpResponse
from wsgiref.util import FileWrapper
from django.contrib.auth.decorators import login_required
from . import ShareManager
import mimetypes
from django.utils.encoding import smart_str
import os
# Create your views here.


    
def index(request):
    if request.user.is_authenticated():
        return redirect('FarboxWeb:home')
    else:
        return redirect('FarboxWeb:login')


def register(request):
    if request.user.is_authenticated():
        logout_user(request)
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.email = form.cleaned_data['email']
            user.save()
            FileManager.create_user_root_dir(user.username)
            messages.info(request, '注册成功!')
            return redirect('FarboxWeb:index')
        return render(request, 'register.html', {
            'form':form,
        })
    else:
        form = RegistrationForm()
        return render(request, 'register.html', {
            'form':form,
        })


def login(request):
    if request.user.is_authenticated():
        logout_user(request)
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if(form.is_valid()):
            if not form.cleaned_data.get('remember_me'):
                request.session.set_expiry(0)
            login_user(request, form.get_user())
            try:
                return redirect(request.GET['next'])
            except:
                return redirect('FarboxWeb:home')
        else:
            msg = "用户名和密码不匹配!"
            return render(request, 'login.html', {
                'form':form,
                'msg':msg,
            })
    else:
        form = LoginForm()
        return render(request, 'login.html', {'form':form,})


@login_required
def home(request):
    username = request.user.get_username()
    try:
        files = VirtualFile.objects.get(parent_id=0, path_name=username)
    except:
        files = VirtualFile(parent_id=0, path_name=username)
        files.save()
    files = VirtualFile.objects.filter(parent_id=files.path_id)
    return render(request, 'home.html', {
        'username': username,
        'files':files,
    })


@login_required
def share_file(request):
    username = request.user.get_username()
    fileid = request.GET['fileid']
    share_info = ShareManager.generate_share_info(fileid)
    share_info.save()
    return render(request, 'share_key.html', {
        'username': username,
        'share_key':share_info.share_key,
    })


@login_required
def share_page(request):
    share_key = request.GET['share_key']
    share_info = ShareInfo.objects.get(pk=share_key)
    file = VirtualFile.objects.get(path_id=share_info.path_id)
    return render(request, 'share_page.html', {
        'username':request.user.get_username(),
        'file':file,
        'share_key':share_key
    })


@login_required
def save_to_mine(request):
    share_key = request.GET['share_key']
    share_info = ShareInfo.objects.get(pk=share_key)
    virtualfile = VirtualFile.objects.get(path_id=share_info.path_id)
    realfile = RealFile.objects.get(file_hash=virtualfile.realfilename)
    FileManager.save_virtual_file(realfile, request.user.get_username())
    return redirect('FarboxWeb:home')


@login_required
def logout(request):
    logout_user(request)
    return redirect('FarboxWeb:index')


@login_required
def upload(request):

    if not request.user.is_authenticated():
        return HttpResponse("you are not logged in")
    if request.method == 'POST':
        try:
            f = request.FILES['file']
        except:
            return redirect('FarboxWeb:upload')
        FileManager.handle_upload_file(f, request.user.get_username())

        return redirect('FarboxWeb:home')
        #return HttpResponse(request.FILES['file'].name + " SIZE: " + str(request.FILES['file'].size))
    else:
        upload_form = UploadForm()
        return render(request, 'upload.html', {'upload_form':upload_form, 'username':request.user.get_username()})


@login_required
def delete_file(request):
    FileManager.delete_file(request.GET['fileid'])
    return redirect('FarboxWeb:home')


def download(request):
    FILE_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)),
                             'UPLOAD_FILES')
    rf = VirtualFile.objects.get(path_id=request.GET['fileid'])
    filename = os.path.join(FILE_PATH, rf.realfilename)
    wrapper = FileWrapper(open(filename, 'rb'))
    response = HttpResponse(wrapper, content_type='application/octet-stream')
    response['Content-Length'] = os.path.getsize(filename)
    response['Content-Disposition'] = ('attachment; filename=%s' % rf.path_name).encode('utf-8')
    return response

farbox/farbox/views.py
from django.http import HttpResponse

farbox/FarboxWeb/templates/home.html
{% load staticfiles %}
<html lang="en">

<head>
  <title>farbox - 在云端的生活</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
   <script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static 'FarboxWeb/bootstrap/css/bootstrap.min.css' %}"/>
    <script src="{% static 'FarboxWeb/bootstrap/js/bootstrap.min.js' %}"> </script>
</head>

<body>
{% csrf_token %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'FarboxWeb:home' %}">Farbox</a>
    </div>
         <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               <span class="glyphicon glyphicon-user"></span>{{ username }}
               <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li><a href="#">个人资料</a></li>
               <li class="divider"></li>
               <li><a href="#">好友</a></li>
            </ul>
          <li><a href="{% url 'FarboxWeb:logout' %}"><span class="glyphicon glyphicon-log-out"></span> logout</a></li>
          </ul>
    </div>
  </div>
</nav>

<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>文件名</th>
        <th>文件大小</th>
        <th>日期</th>
      </tr>
    </thead>
    <tbody>
        {% for file in files %}
            <tr>
                <td><a href="download/?fileid={{file.path_id}}">{{ file.path_name }}</a></td>
                <td>{{ file.file_size }} 字节</td>
                <td>{{ file.upload_time|date:"Y年m月d日 H时i分"}}</td>
                <td><a href="share_file/?fileid={{file.path_id}}">分享</a></td>
                <td><a href="delete_file/?fileid={{file.path_id}}">删除</a></td>
            </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
<div class="container">
    <a href="upload" class="btn btn-info" role="button">upload</a>
</div>
<div class="footer" style="position:fixed;bottom:40px;">

            <span class="label label-primary"> &copy; 2016 farbox</span>
            <span class="dot">·</span>
            <a target="_parent" href="{% url 'FarboxWeb:login' %}" class="label label-success bg-info">登录</a>
            <span class="dot">·</span>
            <a target="_parent" href="{% url 'FarboxWeb:register' %}" class="label label-info bg-success">注册</a>
            <span class="dot">·</span>
            <a target="_top" href="#" class="label label-warning bg-warning">关于我们</a>

        </div>

</body>
</html>

farbox/FarboxWeb/templates/index.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html lang="en">

    <head>
        <title>farbox - 在云端的生活</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- 移动设备使用-->
        <link rel="stylesheet" href="{% static 'FarboxWeb/bootstrap/css/bootstrap.min.css' %}"/>
        <script src="{% static 'FarboxWeb/bootstrap/js/bootstrap.min.js' %}"> </script>
    </head>

    <!-- <body background="{% static 'FarboxWeb/bootstrap/pictures/cl.jpg' %}"> -->
    <body >
        {% csrf_token %}
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand bg-warning" href="#" >Farbox</a>
                </div>
        <ul class="nav navbar-nav">
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               <span class="glyphicon glyphicon-user"></span>Home
               <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li><a href="#">版本</a></li>
               <li class="divider"></li>
               <li><a href="#">加入我们</a></li>
               <li class="divider"></li>
               <li><a href="#">其他</a></li>
            </ul>
        </ul>
        <ul class="nav navbar-nav navbar-right" >
            <li><a href="register" class="bg-info"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="login" class="bg-success"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        </ul>
            </div>
        </nav>

        <div class="jumbotron"  >
            <div class="container">
                <h1>Welcome to farbox!</h1>
                <p><a class="btn btn-primary btn-lg" href="my_files" role="button">My files &raquo;</a></p>
            </div>
        </div>


        <div class="container">
            <div class="row">
                <div class="col-md-4" style="background-color:hoary">
                    <h3>让我们拥抱在云端的生活</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4" style="background-color:lavender;">
                    <p class="text-muted lead ">安全、可靠、快速的文件同步和共享。</p>
                    <p class="text-muted">文件组织成资料库。每个资料库可选择性的同步到任意设备。可靠高效的文件同步将提高您的工作效率。</p>
                </div>
            </div>
        </div>

        <!-- 角标的书写 -->
        <div class="footer" style="position:fixed;bottom:40px;">
            <span class="label label-primary"> &copy; 2016 farbox</span>
            <span class="dot">·</span>
            <a target="_parent" href="login" class="label label-success bg-info">登录</a>
            <span class="dot">·</span>
            <a target="_blank" href="register" class="label label-info bg-success">注册</a>
            <span class="dot">·</span>
            <a target="_top" href="aboutus" class="label label-warning bg-warning">关于我们</a>
        </div>

    </body>
</html>

farbox/FarboxWeb/templates/login.html
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="ie6 ielt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="ie7 ielt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="ie8"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
{% load staticfiles %}
{# Load the tag library #}

<head>
<meta charset="utf-8">
<title>Farbox --让我们拥抱云端的生活</title>
        <link rel="stylesheet" type="text/css" href="{% static 'FarboxWeb/css/style.css' %}" />
	    <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- 移动设备使用-->
        <script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
        <link rel="stylesheet" href="{% static 'FarboxWeb/bootstrap/css/bootstrap.min.css' %}"/>
        <script src="{% static 'FarboxWeb/bootstrap/js/bootstrap.min.js' %}"> </script>
</head>
<body>
{% if msg %} <h2 align="middle">{{ msg }}</h2> {% endif %}
<div class="container">
	<section id="content">
		<form action="" method="post">
            {% csrf_token %}
			<h1>登录</h1>
			<div>
				<input type="text" placeholder="Username" required="required" id="id_username" name="username"/>
			</div>
			<div>
				<input type="password" placeholder="Password" required="required" id="id_password" name="password"/>
			</div>
			<div>
				<input type="submit" value="登录" />
				<a href="#">忘记密码?</a >
				<a href="../register">注册</a>
			</div>
		</form><!-- form -->
	</section><!-- content -->
</div><!-- container -->
<div class="footer" style="position:fixed;bottom:40px;">

            <span class="label label-primary"> &copy; 2016 farbox</span>
            <span class="dot">·</span>
            <a target="_parent" href="{% url 'FarboxWeb:login' %}" class="label label-success bg-info">登录</a>
            <span class="dot">·</span>
            <a target="_blank" href="{% url 'FarboxWeb:register' %}" class="label label-info bg-success">注册</a>
            <span class="dot">·</span>
            <a target="_top" href="aboutus" class="label label-warning bg-warning">关于我们</a>

        </div>
</body>
</html>

farbox/FarboxWeb/templates/msg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Msg</title>
</head>
<body>
<h1> {{msg}} </h1>
</body>
</html>

farbox/FarboxWeb/templates/register.html
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="ie6 ielt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="ie7 ielt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="ie8"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
{% load staticfiles %}
{# Load the tag library #}

<head>
<meta charset="utf-8">
<title>Farbox --让我们拥抱云端的生活</title>
     <link rel="stylesheet" type="text/css" href="{% static 'FarboxWeb/css/style.css' %}" />
	    <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- 移动设备使用-->
        <script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
        <link rel="stylesheet" href="{% static 'FarboxWeb/bootstrap/css/bootstrap.min.css' %}"/>
	<script src="{% static 'FarboxWeb/bootstrap/js/bootstrap.min.js' %}"> </script>
</head>
<body>
<div class="container">
	<section id="content">
		<form action="" method="post">
            {% csrf_token %}
            <h1>注册</h1>
		    <div>
				<input type="text" placeholder="Username" required="required" id="id_username" name="username"/>
			</div>
			<div>
				<input type="password" placeholder="Password" required="required" id="id_password1" name="password1"/>
			</div>
            <div>
				<input type="password" placeholder="Password confirmation" required="required" id="id_password2" name="password2"/>
			</div>
            <div>
				<input type="text" placeholder="Email" required="required" id="id_email" name="email"/>
			</div>
			<div>
				<input type="submit" value="注册" />
                <a href="#">忘记密码?</a >
				<a href="../login">登录</a>
			</div>
		</form><!-- form -->
	</section><!-- content -->
</div><!-- container -->
<div class="container">
	<p align="middle">提示:密码至少包含8位字母和数字</p>
</div>
<div class="footer" style="position:fixed;bottom:40px;">

            <span class="label label-primary"> &copy; 2016 farbox</span>
            <span class="dot">·</span>
            <a target="_parent" href="{% url 'FarboxWeb:login' %}" class="label label-success bg-info">登录</a>
            <span class="dot">·</span>
            <a target="_blank" href="{% url 'FarboxWeb:register' %}" class="label label-info bg-success">注册</a>
            <span class="dot">·</span>
            <a target="_top" href="aboutus" class="label label-warning bg-warning">关于我们</a>

        </div>
</body>
</html>

farbox/FarboxWeb/templates/share_key.html
{% load staticfiles %}
<html lang="en">

<head>
  <title>farbox - 在云端的生活</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
   <script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static 'FarboxWeb/bootstrap/css/bootstrap.min.css' %}"/>
    <script src="{% static 'FarboxWeb/bootstrap/js/bootstrap.min.js' %}"> </script>
</head>

<body>
{% csrf_token %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'FarboxWeb:home' %}">Farbox</a>
    </div>
         <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               <span class="glyphicon glyphicon-user"></span>{{ username }}
               <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li><a href="#">个人资料</a></li>
               <li class="divider"></li>
               <li><a href="#">好友</a></li>
            </ul>
          <li><a href="{% url 'FarboxWeb:logout' %}"><span class="glyphicon glyphicon-log-out"></span> logout</a></li>
          </ul>
    </div>
  </div>
</nav>

<div class="container">
    <h1 align="middle" style="color:#000000">分享链接:<a href="../share_page/?share_key={{share_key}}">
        http://{{ request.get_host }}/share_page/?share_key={{share_key}}</a></h1>
</div>

<div class="footer" style="position:fixed;bottom:40px;">

            <span class="label label-primary"> &copy; 2016 farbox</span>
            <span class="dot">·</span>
            <a target="_parent" href="{% url 'FarboxWeb:login' %}" class="label label-success bg-info">登录</a>
            <span class="dot">·</span>
            <a target="_blank" href="{% url 'FarboxWeb:register' %}" class="label label-info bg-success">注册</a>
            <span class="dot">·</span>
            <a target="_top" href="aboutus" class="label label-warning bg-warning">关于我们</a>

        </div>

</body>
</html>

farbox/FarboxWeb/templates/share_page.html
{% load staticfiles %}
<html lang="en">

<head>
  <title>farbox - 在云端的生活</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
   <script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static 'FarboxWeb/bootstrap/css/bootstrap.min.css' %}"/>
    <script src="{% static 'FarboxWeb/bootstrap/js/bootstrap.min.js' %}"> </script>
</head>

<body>
{% csrf_token %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'FarboxWeb:home' %}">Farbox</a>
    </div>
         <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               <span class="glyphicon glyphicon-user"></span>{{ username }}
               <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li><a href="#">个人资料</a></li>
               <li class="divider"></li>
               <li><a href="#">好友</a></li>
            </ul>
          <li><a href="{% url 'FarboxWeb:logout' %}"><span class="glyphicon glyphicon-log-out"></span> logout</a></li>
          </ul>
    </div>
  </div>
</nav>

<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>文件名</th>
        <th>文件大小</th>
        <th>日期</th>
      </tr>
    </thead>
    <tbody>
            <tr>
                <td><a href="{% url 'FarboxWeb:download' %}/?fileid={{file.path_id}}">{{ file.path_name }}</a></td>
                <td>{{ file.file_size }} 字节</td>
                <td>{{ file.upload_time|date:"Y年m月d日 H时i分"}}</td>
                <td>
                    <a href="{% url 'FarboxWeb:save_to_mine' %}/?share_key={{share_key}}" class="btn btn-info" role="button">转存</a>
                </td>
            </tr>
    </tbody>
  </table>
</div>

<div class="footer" style="position:fixed;bottom:40px;">

            <span class="label label-primary"> &copy; 2016 farbox</span>
            <span class="dot">·</span>
            <a target="_parent" href="{% url 'FarboxWeb:login' %}" class="label label-success bg-info">登录</a>
            <span class="dot">·</span>
            <a target="_blank" href="{% url 'FarboxWeb:register' %}" class="label label-info bg-success">注册</a>
            <span class="dot">·</span>
            <a target="_top" href="aboutus" class="label label-warning bg-warning">关于我们</a>

        </div>

</body>
</html>

farbox/FarboxWeb/templates/success.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title></title>
</head>
<body>
    <h1>恭喜{{username}},注册成功！</h1>

</form>
</body>
</html>

farbox/FarboxWeb/templates/upload.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
      <head>
        <title>farbox - 在云端的生活</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- 移动设备使用-->
        <script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
        <link rel="stylesheet" href="{% static 'FarboxWeb/bootstrap/css/bootstrap.min.css' %}"/>
        <script src="{% static 'FarboxWeb/bootstrap/js/bootstrap.min.js' %}"> </script>
    </head>

</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'FarboxWeb:home' %}">Farbox</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               <span class="glyphicon glyphicon-user"></span> {{ username }}
               <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li><a href="#">个人资料</a></li>
               <li class="divider"></li>
               <li><a href="#">好友</a></li>
               <li class="divider"></li>
               <li><a href="#">其他</a></li>
              <li class="divider"></li>
               <li><a href="../home">文件列表</a></li>
            </ul>
        <li><a href="{% url 'FarboxWeb:logout' %}"><span class="glyphicon glyphicon-log-out"></span> logout</a></li>
      </ul>
    </div>
  </div>
</nav>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{upload_form.as_p}}
    <input type="submit" value="submit"/>
</form>
<HR align=center width=1150 color=#FFFFFF SIZE=1>
<div class="footer" style="position:fixed;bottom:40px;">

            <span class="label label-primary"> &copy; 2016 farbox</span>
            <span class="dot">·</span>
            <a target="_parent" href="{% url 'FarboxWeb:login' %}" class="label label-success bg-info">登录</a>
            <span class="dot">·</span>
            <a target="_blank" href="{% url 'FarboxWeb:register' %}" class="label label-info bg-success">注册</a>
            <span class="dot">·</span>
            <a target="_top" href="aboutus" class="label label-warning bg-warning">关于我们</a>

        </div>

</body>
</html>